services:
  dtrack-apiserver:
    image: dependencytrack/apiserver:4.11.6
    environment:
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://dtrack-postgres:5432/dtrack
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME=dtrack
      - ALPINE_DATABASE_PASSWORD=dtrack
    depends_on:
      - dtrack-postgres
    ports:
      - "127.0.0.1:${DTRACK_API_PORT:-18081}:8080"

  dtrack-frontend:
    image: dependencytrack/frontend:4.11.6
    environment:
      - API_BASE_URL=http://localhost:${DTRACK_API_PORT:-18081}
    depends_on:
      - dtrack-apiserver
    ports:
      - "127.0.0.1:${DTRACK_UI_PORT:-18082}:8080"

  dtrack-postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=dtrack
      - POSTGRES_USER=dtrack
      - POSTGRES_PASSWORD=dtrack
    volumes:
      - dtrack-postgres-data:/var/lib/postgresql/data

volumes:
  dtrack-postgres-data:
